In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import json

In [7]:
file_paths = {
    'district': '/content/drive/MyDrive/Level_Data_Data_Set/2023 District 18 Student Attributes.json',
    'benchmarks': '/content/drive/MyDrive/Level_Data_Data_Set/benchmarks_district 18.json',
    'schools': '/content/drive/MyDrive/Level_Data_Data_Set/District 18 Anonymized Schools.json',
    'vendor_student_usage': '/content/drive/MyDrive/Level_Data_Data_Set/2023 District 18 Vendor Student Usage.json',
    'vendor_usage_types': '/content/drive/MyDrive/Level_Data_Data_Set/District 18 Vendor Usage Types.json'
}

In [11]:
file_paths['student_attributes'] = '/content/drive/MyDrive/Level_Data_Data_Set/Student Attributes.xlsx'
file_paths['student_custom_attribute_types'] = '/content/drive/MyDrive/Level_Data_Data_Set/studentCustomAttributeTypes_district 18.csv'

student_attributes_df = pd.read_excel(file_paths['student_attributes'])
student_custom_attribute_types_df = pd.read_csv(file_paths['student_custom_attribute_types'])

In [12]:
student_custom_attribute_types_df.head()

    id  districtId                    name  value
0   84          18  3rd Grade Literacy Act      1
1   86          18            Intervention      2
2  149          18                  Race B      3
3  150          18                  Race W      4
4  151          18                  Race I      5

In [13]:
student_attributes_df.head()

            ell                           English language learner
0     ethnicity                                                NaN
1        gender                                                NaN
2  lunch status  Indicates whether free/reduced lunch status is...
3    special Ed  Whether a student is enrolled in special educa...

**Load district data, from 2023 District 18 Student Attributes.json**

Setup Dataframe

In [14]:
with open(file_paths['district']) as json_data:
    district_json = json.load(json_data)

    print(pd.DataFrame(district_json) )

    SELECT s.districtId, sc.studentId, sc.`year` , sc.value \r\nFROM aim2.students s\r\nJOIN aim2.studentCustomAttributes sc ON s.id = sc.studentId \r\nWHERE s.districtId = 18
0    {'districtId': 18, 'studentId': 1480395, 'year...
1    {'districtId': 18, 'studentId': 1480554, 'year...
2    {'districtId': 18, 'studentId': 1480554, 'year...
3    {'districtId': 18, 'studentId': 1481892, 'year...
4    {'districtId': 18, 'studentId': 1482258, 'year...
..                                                 ...
332  {'districtId': 18, 'studentId': 1803970, 'year...
333  {'districtId': 18, 'studentId': 1804021, 'year...
334  {'districtId': 18, 'studentId': 1804027, 'year...
335  {'districtId': 18, 'studentId': 1804048, 'year...
336  {'districtId': 18, 'studentId': 2513269, 'year...

[337 rows x 1 columns]

In [15]:
# Get the key for the data (which is a SQL query in this case)
data_key = list(district_json.keys())[0]

# Access the list of records associated with the key
records = district_json[data_key]

# Create a DataFrame
df_district = pd.DataFrame(records)

df_district.head()

   districtId  studentId  year  value
0          18    1480395  2023     12
1          18    1480554  2023     11
2          18    1480554  2023     12
3          18    1481892  2023     11
4          18    1482258  2023     11

In [16]:
df_district.isnull().sum()

districtId    0
studentId     0
year          0
value         0
dtype: int64

**Analyzing the data**

In [17]:
df_district.shape

(337, 4)

In [18]:
df_district.describe()

       districtId     studentId    year       value
count       337.0  3.370000e+02   337.0  337.000000
mean         18.0  1.508344e+06  2023.0   11.397626
std           0.0  9.456089e+04     0.0    0.490135
min          18.0  1.480395e+06  2023.0   11.000000
25%          18.0  1.483957e+06  2023.0   11.000000
50%          18.0  1.484869e+06  2023.0   11.000000
75%          18.0  1.487114e+06  2023.0   12.000000
max          18.0  2.513269e+06  2023.0   12.000000

**Load benchmarks_district 18.json**

In [19]:
with open(file_paths['benchmarks']) as json_data:
    benchmarks_json = json.load(json_data)

    print(pd.DataFrame(benchmarks_json) )

                                            benchmarks
0    {'id': 120, 'districtId': 18, 'year': 2017, 'l...
1    {'id': 121, 'districtId': 18, 'year': 2017, 'l...
2    {'id': 122, 'districtId': 18, 'year': 2017, 'l...
3    {'id': 123, 'districtId': 18, 'year': 2017, 'l...
4    {'id': 124, 'districtId': 18, 'year': 2017, 'l...
..                                                 ...
830  {'id': 49566, 'districtId': 18, 'year': 2023, ...
831  {'id': 49570, 'districtId': 18, 'year': 2023, ...
832  {'id': 49574, 'districtId': 18, 'year': 2023, ...
833  {'id': 5309553, 'districtId': 18, 'year': 2023...
834  {'id': 5309646, 'districtId': 18, 'year': 2023...

[835 rows x 1 columns]

In [20]:
# Get the key for the data (which is a SQL query in this case)
data_key = list(benchmarks_json.keys())[0]

# Access the list of records associated with the key
records = benchmarks_json[data_key]

# Create a DataFrame
df_benchmarks = pd.DataFrame(records)

df_benchmarks.head()

    id  districtId  year  level             dataSource   value
0  120          18  2017      3     value_scantronMath  2355.0
1  121          18  2017      3  value_scantronReading  2562.0
2  122          18  2017      4     value_scantronMath  2492.0
3  123          18  2017      4  value_scantronReading  2673.0
4  124          18  2017      5     value_scantronMath  2583.0

In [21]:
print("Benchmarks DataFrame Shape:", df_benchmarks.shape)
print("Columns in the Benchmarks DataFrame:", df_benchmarks.columns.tolist())

Benchmarks DataFrame Shape: (835, 6)
Columns in the Benchmarks DataFrame: ['id', 'districtId', 'year', 'level', 'dataSource', 'value']

In [22]:
# Counts the occurrences of each DataSource value
datasource_counts = df_benchmarks['dataSource'].value_counts()
datasource_counts

dataSource
value_starMath                   51
value_starReading                44
value_starReadingUnified         42
value_acapLexile                 39
value_starMathUnified            38
value_scantronMath               35
value_acapELALevel               35
value_acapMathLevel              35
value_acapMath                   35
value_acapELA                    35
value_scantronReading            34
value_edulasticELA               27
value_edulasticMath              27
value_lexileStar                 27
value_StarEarlyLit               23
value_actCompositeScore          21
value_actReadingScore            21
value_actMathScore               21
value_actEnglishScore            21
value_actScienceScore            19
value_acapScience                15
value_iReadyMath                 13
value_edulasticScience           12
value_acapScienceLevel           12
value_iReadyReading              12
value_starEarlyLitUnified         9
value_edulasticPhySci             8
value_edulasticGov                8
value_edulasticUsHistory          8
value_edulasticEco                8
value_edulasticWH                 8
value_edulasticEnvironmental      8
value_edulasticChem               8
value_edulasticBio                8
value_edulasticAlgebra            8
value_edulasticGeography          8
value_edulasticCivics             8
value_edulasticHistory            8
value_StudySyncELA                6
value_aspireReadingScaleScore     6
value_edulasticGeometry           4
value_beableAcademic              4
value_edulasticPreCal             4
value_edulasticAP                 4
value_actELA                      4
value_actELAScore                 2
value_acapReadSubscore            2
Name: count, dtype: int64

In [23]:
df_benchmarks.describe(include='all')

,id,districtId,year,level,dataSource,value
count,8.350000e+02,835.0,835.000000,835.000000,835,835.000000
unique,NaN,NaN,NaN,NaN,47,NaN
top,NaN,NaN,NaN,NaN,value_starMath,NaN
freq,NaN,NaN,NaN,NaN,51,NaN
mean,5.891713e+05,18.0,2021.341317,6.853892,NaN,582.857951
std,1.631435e+06,0.0,1.504480,3.352256,NaN,739.631078
min,1.200000e+02,18.0,2017.000000,0.000000,NaN,2.900000
25%,7.208500e+03,18.0,2020.000000,4.000000,NaN,70.000000
50%,2.377900e+04,18.0,2022.000000,7.000000,NaN,476.000000
75%,4.826250e+04,18.0,2023.000000,10.000000,NaN,841.000000
max,5.309646e+06,18.0,2023.000000,12.000000,NaN,3062.000000

**New table made with benchmarks from 2023**

In [24]:
table_data = []  # List to store the table data

for (datasource, level, year), group in df_benchmarks.groupby(['dataSource', 'level', 'year']):
    if year == 2023:
        for index, row in group.iterrows():  # Iterate through rows in the group
            table_data.append({
                'DataSource': datasource,
                'Level': level,
                'Year': year,
                'id': row['id'],
                'districtId': row['districtId'],
                'value': row['value']
                # Add other columns you want to include in the table
            })

# Create a DataFrame from the table data
table_df = pd.DataFrame(table_data)


table_df.head()

           DataSource  Level  Year       id  districtId  value
0  value_StarEarlyLit      1  2023  5306131          18  743.0
1  value_StudySyncELA      6  2023    48057          18   70.0
2  value_StudySyncELA      7  2023    48058          18   70.0
3  value_StudySyncELA      8  2023    48059          18   70.0
4       value_acapELA      2  2023    53798          18  501.0

**Loading District 18 Anonymized Schools**

In [25]:
with open(file_paths['schools']) as json_data:
    schools_json = json.load(json_data)

    print(pd.DataFrame(schools_json) )

                                              schools
0   {'id': 222, 'name': 'ELEMENTARY SCHOOL A', 'di...
1   {'id': 223, 'name': 'MIDDLE SCHOOL A', 'distri...
2   {'id': 224, 'name': 'HIGH SCHOOL A', 'district...
3   {'id': 225, 'name': 'JUNIOR HIGH B', 'district...
4   {'id': 226, 'name': 'ELEMENTARY SCHOOL B', 'di...
5   {'id': 227, 'name': 'MIDDLE SCHOOL B', 'distri...
6   {'id': 228, 'name': 'HIGH SCHOOL B', 'district...
7   {'id': 229, 'name': 'MIDDLE SCHOOL C', 'distri...
8   {'id': 230, 'name': 'ELEMENTARY SCHOOL C', 'di...
9   {'id': 231, 'name': 'ELEMENTARY SCHOOL D', 'di...
10  {'id': 232, 'name': 'INTERMEDIATE SCHOOL D', '...
11  {'id': 233, 'name': 'HIGH SCHOOL C', 'district...
12  {'id': 234, 'name': 'ELEMENTARY SCHOOL E', 'di...
13  {'id': 235, 'name': 'ELEMENTARY SCHOOL F', 'di...
14  {'id': 236, 'name': 'HIGH SCHOOL D', 'district...
15  {'id': 237, 'name': 'MIDDLE SCHOOL E', 'distri...
16  {'id': 238, 'name': 'JUNIOR HIGH SCHOOL F', 'd...
17  {'id': 247, 'name': 'Instructional Services', ...
18  {'id': 248, 'name': 'Instructional Support Ser...
19  {'id': 249, 'name': 'General and Administrativ...
20  {'id': 1346, 'name': 'THE EDGE', 'districtId':...
21  {'id': 46049, 'name': 'MIDDLE SCHOOL G', 'dist...
22  {'id': 282626, 'name': 'TECHNICAL CENTER', 'di...
23  {'id': 282627, 'name': 'Technical College', 'd...

In [26]:
# Get the key for the data (which is a SQL query in this case)
data_key = list(schools_json.keys())[0]

# Access the list of records associated with the key
records = schools_json[data_key]

# Create a DataFrame
df_schools = pd.DataFrame(records)

df_schools.head()

,id,name,districtId,costCenter,abbreviation,acqRequestSelectable,oneRoster_sourcedId,oneRoster_ticketId
0,222,ELEMENTARY SCHOOL A,18,5,EES,1,,0
1,223,MIDDLE SCHOOL A,18,8,EMS,1,,0
2,224,HIGH SCHOOL A,18,10,ECHS,1,,0
3,225,JUNIOR HIGH B,18,12,ECJH,1,,0
4,226,ELEMENTARY SCHOOL B,18,18,HES,1,,0

In [27]:
print("Schools DataFrame Shape:", df_schools.shape)
print("Columns in the Schools DataFrame:", df_schools.columns.tolist())

Schools DataFrame Shape: (24, 8)
Columns in the Schools DataFrame: ['id', 'name', 'districtId', 'costCenter', 'abbreviation', 'acqRequestSelectable', 'oneRoster_sourcedId', 'oneRoster_ticketId']

In [28]:
df_schools.describe(include='all')

,id,name,districtId,costCenter,abbreviation,acqRequestSelectable,oneRoster_sourcedId,oneRoster_ticketId
count,24.000000,24,24.0,24.000000,24,24.000000,24,24
unique,NaN,24,NaN,NaN,21,NaN,1,2
top,NaN,ELEMENTARY SCHOOL A,NaN,NaN,,NaN,,0
freq,NaN,1,NaN,NaN,4,NaN,24,21
mean,25720.916667,NaN,18.0,1066.125000,NaN,0.833333,NaN,NaN
std,79673.603191,NaN,0.0,2794.158181,NaN,0.380693,NaN,NaN
min,222.000000,NaN,18.0,0.000000,NaN,0.000000,NaN,NaN
25%,227.750000,NaN,18.0,11.500000,NaN,1.000000,NaN,NaN
50%,233.500000,NaN,18.0,32.500000,NaN,1.000000,NaN,NaN
75%,247.250000,NaN,18.0,66.250000,NaN,1.000000,NaN,NaN
max,282627.000000,NaN,18.0,8600.000000,NaN,1.000000,NaN,NaN

**Load vendor_student_usage**

In [29]:
with open(file_paths['vendor_student_usage']) as json_data:
    vsu_json = json.load(json_data)

    print(pd.DataFrame(vsu_json) )

      SELECT s.districtId, sc.studentId, sc.`year` , sc.vendorId, sc.active, sc.usageTypeId, sc.weeklyUsageMinutes \r\nFROM aim2.students s\r\nJOIN aim2.vendorStudentUsage sc ON s.id = sc.studentId \r\nWHERE s.districtId = 18 AND sc.`year` = 2023
0      {'districtId': 18, 'studentId': 1480117, 'year...
1      {'districtId': 18, 'studentId': 1480117, 'year...
2      {'districtId': 18, 'studentId': 1480117, 'year...
3      {'districtId': 18, 'studentId': 1480118, 'year...
4      {'districtId': 18, 'studentId': 1480118, 'year...
...                                                  ...
70310  {'districtId': 18, 'studentId': 1804199, 'year...
70311  {'districtId': 18, 'studentId': 1804199, 'year...
70312  {'districtId': 18, 'studentId': 1804201, 'year...
70313  {'districtId': 18, 'studentId': 1804201, 'year...
70314  {'districtId': 18, 'studentId': 1804201, 'year...

[70315 rows x 1 columns]

In [30]:
# Get the key for the data (which is a SQL query in this case)
data_key = list(vsu_json.keys())[0]

# Access the list of records associated with the key
records = vsu_json[data_key]

# Create a DataFrame
df_vsu = pd.DataFrame(records)

df_vsu.head(25)

,districtId,studentId,year,vendorId,active,usageTypeId,weeklyUsageMinutes
0,18,1480117,2023,140472,0,39,4
1,18,1480117,2023,11333,0,6,0
2,18,1480117,2023,72609,0,3,0
3,18,1480118,2023,140472,0,39,4
4,18,1480118,2023,11333,0,6,0
5,18,1480118,2023,72609,0,3,0
6,18,1480120,2023,140472,0,39,4
7,18,1480120,2023,11333,0,6,104
8,18,1480120,2023,72609,0,3,0
9,18,1480121,2023,140472,0,39,4
10,18,1480121,2023,11333,0,6,181
11,18,1480121,2023,72609,0,3,0
12,18,1480122,2023,140472,0,39,4
13,18,1480122,2023,11333,0,6,0
14,18,1480122,2023,72609,0,3,0
15,18,1480123,2023,140472,0,39,4
16,18,1480123,2023,11333,0,6,0
17,18,1480123,2023,72609,0,3,22
18,18,1480124,2023,140472,0,39,4
19,18,1480124,2023,11333,0,6,0
20,18,1480124,2023,72609,0,3,26
21,18,1480125,2023,140472,0,39,4
22,18,1480125,2023,11333,0,6,0
23,18,1480125,2023,72609,0,3,0
24,18,1480126,2023,140472,0,39,4

In [36]:
# Count the occurrences of each studentId in the df_vsu DataFrame
df_vsu['studentId'].value_counts()

studentId
1491261    14
1485839    13
1485973    13
1487798    13
1488235    13
           ..
1480380     1
1480381     1
1481481     1
1480383     1
1481904     1
Name: count, Length: 11654, dtype: int64

In [38]:
# Create a table with df_vsu['studentId']
student_id_table = pd.DataFrame({'studentId': df_vsu['studentId'].unique()})

student_id_table

       studentId
0        1480117
1        1480118
2        1480120
3        1480121
4        1480122
...          ...
11649    1804195
11650    1804197
11651    1804198
11652    1804199
11653    1804201

[11654 rows x 1 columns]

In [39]:
# studentId most occurance
# Count the occurrences of each studentId
studentId_counts = df_vsu['studentId'].value_counts()

# Find the studentId with the most occurrences
most_frequent_studentId = studentId_counts.idxmax()

print(f"The studentId with the most occurrences is: {most_frequent_studentId}")

The studentId with the most occurrences is: 1491261

In [40]:
#generate information on studentId 1491261

# Filter the df_vsu DataFrame to include only rows where studentId is 1491261
student_1491261_df = df_vsu[df_vsu['studentId'] == 1491261]

# Display the filtered DataFrame
print(student_1491261_df)

# You can also analyze specific columns for this student
print("\nUsage types for student 1491261:")
print(student_1491261_df['usageTypeId'].value_counts())

# If you want to find more information about this student, you can look into the
# student_attributes_df using the studentId (if available in that dataframe)
# For example:
# student_info = student_attributes_df[student_attributes_df['studentId'] == 1491261]
# print("\nStudent information (if available):")
# print(student_info)

       districtId  studentId  year  vendorId  active  usageTypeId  \
54930          18    1491261  2023    132810       0            1
54931          18    1491261  2023    132810       0            6
54932          18    1491261  2023     11333       0            5
54933          18    1491261  2023     72609       0            1
54934          18    1491261  2023    138965       0            9
54935          18    1491261  2023    132795       0            9
54936          18    1491261  2023    132795       0            9
54937          18    1491261  2023    140472       0           38
54938          18    1491261  2023     11333       0            5
54939          18    1491261  2023     72609       0            3
54940          18    1491261  2023     11333       0           24
54941          18    1491261  2023     11333       0           27
54942          18    1491261  2023    140574       0           41
54943          18    1491261  2023    140574       0           42

       weeklyUsageMinutes
54930                   0
54931                   0
54932                   0
54933                   0
54934                   0
54935                   0
54936                   0
54937                  33
54938                1036
54939                 557
54940                   6
54941                   0
54942                   0
54943                   0

Usage types for student 1491261:
usageTypeId
9     3
1     2
5     2
6     1
38    1
3     1
24    1
27    1
41    1
42    1
Name: count, dtype: int64

In [55]:
df_vsu.shape

(70315, 7)

In [56]:
df_vsu.columns.tolist()

['districtId',
 'studentId',
 'year',
 'vendorId',
 'active',
 'usageTypeId',
 'weeklyUsageMinutes']

In [57]:
df_vsu.isnull().sum()

districtId            0
studentId             0
year                  0
vendorId              0
active                0
usageTypeId           0
weeklyUsageMinutes    0
dtype: int64

In [58]:
df_vsu.dtypes

districtId            int64
studentId             int64
year                  int64
vendorId              int64
active                int64
usageTypeId           int64
weeklyUsageMinutes    int64
dtype: object

In [59]:
df_vsu.describe()

,districtId,studentId,year,vendorId,active,usageTypeId,weeklyUsageMinutes
count,70315.0,7.031500e+04,70315.0,70315.000000,70315.0,70315.000000,70315.000000
mean,18.0,1.533511e+06,2023.0,60604.109180,0.0,16.483880,255.321169
std,0.0,1.122787e+05,0.0,52670.977558,0.0,15.599277,646.739499
min,18.0,1.480117e+06,2023.0,11333.000000,0.0,1.000000,0.000000
25%,18.0,1.484799e+06,2023.0,11333.000000,0.0,3.000000,0.000000
50%,18.0,1.487708e+06,2023.0,72609.000000,0.0,6.000000,0.000000
75%,18.0,1.490802e+06,2023.0,132795.000000,0.0,27.000000,84.000000
max,18.0,1.804201e+06,2023.0,140574.000000,0.0,42.000000,9631.000000

**Load vendor_usage_types**

In [8]:
with open(file_paths['vendor_usage_types']) as json_data:
    vut_json = json.load(json_data)

    print(pd.DataFrame(vut_json) )

                                      vendorUsageTypes
0    {'id': 4, 'name': 'IXL Reading Non', 'district...
1    {'id': 5, 'name': 'IXL Reading Partial', 'dist...
2    {'id': 6, 'name': 'IXL Reading User', 'distric...
3    {'id': 7, 'name': 'IXL Math Non User', 'distri...
4    {'id': 8, 'name': 'IXL Math Partial ', 'distri...
..                                                 ...
285  {'id': 14805, 'name': 'IXL Reading Partial', '...
286  {'id': 14806, 'name': 'IXL Reading User', 'dis...
287  {'id': 14807, 'name': 'IXL Reading Non', 'dist...
288  {'id': 14808, 'name': 'IXL Reading Partial', '...
289  {'id': 14809, 'name': 'IXL Reading User', 'dis...

[290 rows x 1 columns]

In [61]:
# Get the key for the data (which is a SQL query in this case)
data_key = list(vut_json.keys())[0]

# Access the list of records associated with the key
records = vut_json[data_key]

# Create a DataFrame
df_vut = pd.DataFrame(records)

df_vut.head(10)

,id,name,districtId,usageTypeId,roiBucketType,initiativeId,vendorId,utilBucketType,weeklyUsageMinutes,productId
0,4,IXL Reading Non,18,1,loss,61,72609,nonUser,0,0
1,5,IXL Reading Partial,18,2,loss,61,72609,partialUser,0,0
2,6,IXL Reading User,18,3,gain,61,72609,fullUser,0,0
3,7,IXL Math Non User,18,4,loss,60,11333,nonUser,0,0
4,8,IXL Math Partial,18,5,loss,60,11333,partialUser,0,0
5,9,IXL Math User,18,6,gain,60,11333,fullUser,0,0
6,175,IXL Reading Non,18,1,loss,470,72609,nonUser,0,0
7,176,IXL Math User,18,6,gain,471,11333,fullUser,0,0
8,177,IXL Reading Partial,18,2,loss,470,72609,partialUser,0,0
9,178,IXL Reading User,18,3,gain,470,72609,fullUser,0,0

In [62]:
df_vut.shape

(290, 10)

In [63]:
df_vut.columns.tolist()

['id',
 'name',
 'districtId',
 'usageTypeId',
 'roiBucketType',
 'initiativeId',
 'vendorId',
 'utilBucketType',
 'weeklyUsageMinutes',
 'productId']

In [64]:
df_vut.isnull().sum()

id                    0
name                  0
districtId            0
usageTypeId           0
roiBucketType         0
initiativeId          0
vendorId              0
utilBucketType        0
weeklyUsageMinutes    0
productId             0
dtype: int64

In [65]:
df_vut.dtypes

id                     int64
name                  object
districtId             int64
usageTypeId            int64
roiBucketType         object
initiativeId           int64
vendorId               int64
utilBucketType        object
weeklyUsageMinutes     int64
productId              int64
dtype: object

In [66]:
df_vut.describe(include = 'all')

,id,name,districtId,usageTypeId,roiBucketType,initiativeId,vendorId,utilBucketType,weeklyUsageMinutes,productId
count,290.000000,290,290.0,290.000000,290,290.000000,290.000000,290,290.0,290.0
unique,NaN,45,NaN,NaN,2,NaN,NaN,3,NaN,NaN
top,NaN,IXL Reading Partial,NaN,NaN,loss,NaN,NaN,partialUser,NaN,NaN
freq,NaN,20,NaN,NaN,193,NaN,NaN,97,NaN,NaN
mean,6100.951724,NaN,18.0,18.393103,NaN,1652.265517,105957.382759,NaN,0.0,0.0
std,4507.983829,NaN,0.0,15.776684,NaN,1108.869549,44901.895280,NaN,0.0,0.0
min,4.000000,NaN,18.0,1.000000,NaN,0.000000,11333.000000,NaN,0.0,0.0
25%,2350.250000,NaN,18.0,5.000000,NaN,592.750000,72609.000000,NaN,0.0,0.0
50%,4342.500000,NaN,18.0,11.000000,NaN,1714.000000,131391.000000,NaN,0.0,0.0
75%,11295.750000,NaN,18.0,37.000000,NaN,2437.000000,140472.000000,NaN,0.0,0.0
max,14809.000000,NaN,18.0,45.000000,NaN,4081.000000,140575.000000,NaN,0.0,0.0

In [67]:
file_paths['scores'] = '/content/drive/MyDrive/Level_Data_Data_Set/2023 District 18 Scores.json'

In [68]:
with open(file_paths['scores']) as json_data:
    scores_json = json.load(json_data)

    pd.DataFrame(scores_json)

In [69]:
# Get the key for the data (which is a SQL query in this case)
data_key = list(scores_json.keys())[0]

# Access the list of records associated with the key
records = scores_json[data_key]

# Create a DataFrame
df_scores = pd.DataFrame(records)

df_scores.head(25)

,id,districtId,subgroup_TCAPELALevel,ticket,studentId,studentLevel,year,scoreDate,measurementTypeId,subgroup_specialEd,...,value_ElpacOralLevel,value_ElpacWritten,value_ElpacWrittenLevel,value_AcapSciRc1,value_AcapSciRc2,value_AcapSciRc3,value_AcapSciRc4,value_fsaWriting,value_fsaWritingLevel,value_acadienceReadingCompositeLevel
0,3268686,18,0,1670274005jaxk7kpda0,1480117,11,2023,0000-00-00,4,0,...,0,0,0,0,0,0,0,0,0,0
1,4933778,18,0,,1480117,11,2023,0000-00-00,1,0,...,0,0,0,0,0,0,0,0,0,0
2,5441518,18,0,,1480117,11,2023,0000-00-00,2,0,...,0,0,0,0,0,0,0,0,0,0
3,7263146,18,0,,1480117,11,2023,0000-00-00,6,0,...,0,0,0,0,0,0,0,0,0,0
4,7510656,18,0,,1480117,11,2023,0000-00-00,7,0,...,0,0,0,0,0,0,0,0,0,0
5,7515779,18,0,,1480117,11,2023,0000-00-00,3,0,...,0,0,0,0,0,0,0,0,0,0
6,4933508,18,0,,1480118,12,2023,0000-00-00,1,0,...,0,0,0,0,0,0,0,0,0,0
7,5444101,18,0,,1480118,12,2023,0000-00-00,2,0,...,0,0,0,0,0,0,0,0,0,0
8,4933512,18,0,,1480120,12,2023,0000-00-00,1,0,...,0,0,0,0,0,0,0,0,0,0
9,5442635,18,0,,1480120,12,2023,0000-00-00,2,0,...,0,0,0,0,0,0,0,0,0,0
10,7510657,18,0,,1480120,12,2023,0000-00-00,7,0,...,0,0,0,0,0,0,0,0,0,0
11,7517558,18,0,,1480120,12,2023,0000-00-00,3,0,...,0,0,0,0,0,0,0,0,0,0
12,4933663,18,0,,1480121,12,2023,0000-00-00,1,0,...,0,0,0,0,0,0,0,0,0,0
13,5443912,18,0,,1480121,12,2023,0000-00-00,2,0,...,0,0,0,0,0,0,0,0,0,0
14,7513967,18,0,,1480121,12,2023,0000-00-00,7,0,...,0,0,0,0,0,0,0,0,0,0
15,7517559,18,0,,1480121,12,2023,0000-00-00,3,0,...,0,0,0,0,0,0,0,0,0,0
16,4933502,18,0,,1480122,12,2023,0000-00-00,1,0,...,0,0,0,0,0,0,0,0,0,0
17,5442785,18,0,,1480122,12,2023,0000-00-00,2,0,...,0,0,0,0,0,0,0,0,0,0
18,7513968,18,0,,1480122,12,2023,0000-00-00,7,0,...,0,0,0,0,0,0,0,0,0,0
19,7517560,18,0,,1480122,12,2023,0000-00-00,3,0,...,0,0,0,0,0,0,0,0,0,0
20,4933459,18,0,,1480123,12,2023,0000-00-00,1,0,...,0,0,0,0,0,0,0,0,0,0
21,5442491,18,0,,1480123,12,2023,0000-00-00,2,0,...,0,0,0,0,0,0,0,0,0,0
22,7513969,18,0,,1480123,12,2023,0000-00-00,7,0,...,0,0,0,0,0,0,0,0,0,0
23,7517561,18,0,,1480123,12,2023,0000-00-00,3,0,...,0,0,0,0,0,0,0,0,0,0
24,4933666,18,0,,1480124,12,2023,0000-00-00,1,0,...,0,0,0,0,0,0,0,0,0,0

In [70]:
df_scores.shape

(132258, 715)

In [71]:
df_scores.columns.tolist()

['id',
 'districtId',
 'subgroup_TCAPELALevel',
 'ticket',
 'studentId',
 'studentLevel',
 'year',
 'scoreDate',
 'measurementTypeId',
 'subgroup_specialEd',
 'subgroup_lunchStatus',
 'subgroup_gender',
 'subgroup_ethnicity',
 'subgroup_ell',
 'subGroup_bottom25',
 'value_actMathScore',
 'value_actEnglishScore',
 'value_actReadingScore',
 'value_actScienceScore',
 'value_actCompositeScore',
 'value_nweaMath',
 'value_nweaReading',
 'value_nweaEnglish',
 'value_iReadyMath',
 'value_iReadyReading',
 'value_nweaELA',
 'value_scantronMath',
 'value_scantronReading',
 'value_MAAPMath',
 'value_MAAPRLA',
 'value_scantronScience',
 'value_scantronLanguage',
 'value_ReadingFoundations',
 'value_scantronAlgebra',
 'value_actELAScore',
 'value_MAAPScience',
 'value_accessReadingScale',
 'value_accessReadingProficiency',
 'value_accessCompositeScale',
 'value_accesscompositeProficiency',
 'value_dibelsReading',
 'value_MathMilestones',
 'value_ELAMilestones',
 'value_starReading',
 'value_starMath',
 'value_ScienceMilestones',
 'value_LEAPScience',
 'value_SocialMilestones',
 'value_lexile',
 'value_AlgebraGMA',
 'value_GeometryGMA',
 'value_BiologyGMA',
 'value_EconomicsGMA',
 'value_PhysScienceGMA',
 'value_AmLitGMA',
 'value_9thLitGMA',
 'value_UsHisGMA',
 'value_AnalyticGeoGMA',
 'value_DibelsOrf',
 'value_DibelsLNF',
 'value_DibelsNWF',
 'value_MaapEnglishII',
 'value_MaapAlgI',
 'value_MaapBio',
 'value_MaapUsHis',
 'value_AlgIBenchmark',
 'value_AlgIABenchmark',
 'value_AlgIBBenchmark',
 'value_AlgConnBenchmark',
 'value_AlgIIBenchmark',
 'value_AlgIITrigBenchmark',
 'value_BioBenchmark',
 'value_ChemBenchmark',
 'value_EconomicsBenchmark',
 'value_EnglishBenchmark',
 'value_EnvironmentalBenchmark',
 'value_GeometryBenchmark',
 'value_PhyScienceBenchmark',
 'value_UsGovBenchmark',
 'value_UsHisBenchmark',
 'value_WorldHis9Benchmark',
 'value_MAAPRLAProf',
 'value_MAAPMathProf',
 'value_tcapELA',
 'value_tcapMath',
 'value_tcapScience',
 'value_tcapSocialStudies',
 'value_tcapEnglishI',
 'value_tcapEnglishII',
 'value_tcapAlgebraI',
 'value_tcapAlgebraII',
 'value_tcapGeometry',
 'value_tcapIntMathI',
 'value_tcapIntMathIII',
 'value_tcapIntMathII',
 'value_tcapBiology',
 'value_tcapUSHistory',
 'value_tcapGeography',
 'value_AccessScaleScore',
 'value_AccessProficiency',
 'value_acapELA',
 'value_acapMath',
 'value_nweaScience',
 'value_StarEarlyLit',
 'value_caseAlg',
 'value_caseBio',
 'value_caseEng',
 'value_caseHis',
 'value_caseRead',
 'value_caseMath',
 'value_caseSci',
 'value_gcaInfo',
 'value_gcaNar',
 'value_gcaOpin',
 'value_pivotMath',
 'value_pivotELA',
 'value_elsMath',
 'value_elsEng',
 'value_elsELA',
 'value_elsAlg',
 'value_SATEBRW',
 'value_SATMath',
 'value_transMath',
 'value_SATComposite',
 'value_edmentumMath',
 'value_edmentumReading',
 'value_edmentumELA',
 'value_mStepMath',
 'value_mStepELA',
 'value_mStepSocial',
 'value_lexia',
 'value_PSATComposite',
 'value_PSATMath',
 'value_PSATEBRW',
 'value_gcaEng',
 'value_gcaAlg',
 'value_gcaBio',
 'value_gcaEcon',
 'value_gcaPhysSci',
 'value_gcaMath',
 'value_gcaELA',
 'value_gcaScience',
 'value_gcaSocial',
 'value_gcaUsHis',
 'value_iarELA',
 'value_iarMath',
 'value_gcaGeo',
 'value_edulasticELA',
 'value_drcELA',
 'value_drcMath',
 'value_iStationReading',
 'value_iStationMath',
 'value_iStationReadingLevel',
 'value_iStationMathLevel',
 'value_BeaconELA',
 'value_BeaconMath',
 'value_DibelsComposite',
 'value_StarMathGLE',
 'value_StarReadingGLE',
 'value_StarEarlyLitGLE',
 'value_LexiaCore',
 'value_LexiaPower',
 'value_imagineLiteracy',
 'value_CaseMathPercentCorrect',
 'value_CaseReadPercentCorrect',
 'value_PSF',
 'value_LNF',
 'value_LWSF',
 'value_WRF',
 'value_NWF',
 'value_ORF',
 'value_Voc',
 'value_NNF',
 'value_Ca',
 'value_QTF',
 'value_QDF',
 'value_NCFT',
 'value_NCFP',
 'value_MFF1D',
 'value_MFFT',
 'value_CaseAlgPercentCorrect',
 'value_CaseBioPercentCorrect',
 'value_CaseEngIIPercentCorrect',
 'value_CaseUsHisPercentCorrect',
 'value_NSF',
 'value_MCF',
 'value_ENB',
 'value_MathB',
 'value_elsBio',
 'value_MasteryPrepComposite',
 'value_MasteryPrepEnglish',
 'value_MasteryPrepMath',
 'value_MasteryPrepReading',
 'value_MasteryPrepScience',
 'value_actSuperscore',
 'value_actStemScore',
 'value_MathInventory',
 'value_ReadingInventory',
 'value_DibelsPSF',
 'value_DibelsWRF',
 'value_DibelsMAZE',
 'subgroup_TCAPMathLevel',
 'value_TCAPELALevel',
 'value_TCAPMathLevel',
 'value_SummerELA',
 'value_SummerMath',
 'value_AandPBenchmark',
 'value_UsHisIIBenchmark',
 'value_acapMathLevel',
 'value_acapELALevel',
 'value_EarthSpaceBenchmark',
 'value_PreCalBenchmark',
 'value_ELAMilestonesLevel',
 'value_MathMilestonesLevel',
 'value_acapScience',
 'value_SciMilestonesLevel',
 'value_SocMilestonesLevel',
 'value_IXLELA',
 'value_IXLMath',
 'value_DibelsNWFWRC',
 'value_DibelsOrfWC',
 'value_CertReading',
 'value_CertMath',
 'value_CertScience',
 'value_CertEnglish',
 'value_CertComposite',
 'value_aimsReading',
 'value_aimsMath',
 'value_acapScienceLevel',
 'value_performanceReading',
 'value_fsaELA',
 'value_fsaELALevel',
 'value_fsaMath',
 'value_fsaMathLevel',
 'value_fsaAlgI',
 'value_fsaBio',
 'value_fsaUsHis',
 'value_edulasticMath',
 'value_AmericanHistoryBenchmark',
 'value_performanceMath',
 'value_performanceEnglish',
 'value_performanceScience',
 'value_performanceSS',
 'value_performanceUsHis',
 'value_performanceWH',
 'value_widaListening',
 'value_widaReading',
 'value_widaSpeaking',
 'value_widaWriting',
 'value_widaLiteracy',
 'value_widaComposite',
 'value_schoolNetELA',
 'value_schoolNetMath',
 'value_acadienceReadingComposite',
 'value_elsELALevel',
 'value_elsMathLevel',
 'value_MAAPHistory',
 'value_caseEngII',
 'value_HMHReading',
 'value_IXLScience',
 'value_performanceCivics',
 'value_performanceGeo',
 'value_performancePhysSci',
 'value_performanceBio',
 'value_performanceGov',
 'value_elsEngLevel',
 'value_elsBioLevel',
 'value_elsAlgLevel',
 'value_elsUsHis',
 'value_elsUsHisLevel',
 'value_ReadingPlus',
 'value_edulasticScience',
 'value_edulasticHistory',
 'value_classworksELA',
 'value_classworksMath',
 'value_KReadiness',
 'value_illuminateMath',
 'value_illuminateReading',
 'value_illuminateUsHis',
 'value_illuminateAlg',
 'value_CBMLn',
 'value_CBMBasicMath',
 'value_CBMProfRdg',
 'value_CBMPs',
 'value_CBMPrf',
 'value_CBMLs',
 'value_TScore',
 'value_illuminateBio',
 'value_illuminateScience',
 'value_OTCScience',
 'value_OTCMath',
 'value_OTCEnglish',
 'value_nweaReadingSpanish',
 'value_nweaMathSpanish',
 'value_nweaReadingProjected',
 'value_nweaMathProjected',
 'value_nweaProjectedMathSpanish',
 'value_nweaProjectedReadingSpanish',
 'value_ProjectedMAAPELA',
 'value_ProjectedMAAPMath',
 'value_acapReadSubscore',
 'value_accuplacerComposite',
 'value_caseReadLevel',
 'value_caseMathLevel',
 'value_caseAlgLevel',
 'value_caseBioLevel',
 'value_caseEngIILevel',
 'value_caseSciLevel',
 'value_caseHisLevel',
 'value_noAssessment',
 'value_schoolNetScience',
 'value_schoolNetEngII',
 'value_schoolNetEngI',
 'value_schoolNetGeo',
 'value_schoolNetAlgII',
 'value_schoolNetSS',
 'value_schoolNetBio',
 'value_schoolNetAlgI',
 'value_MaapEnglishIIProf',
 'value_MaapAlgIProf',
 'value_MaapBioProf',
 'value_MAAPScienceProf',
 'value_TCAPScienceLevel',
 'value_TCAPSocialLevel',
 'value_MaapUsHisProf',
 'value_AlgebraGMALevel',
 'value_AmLitGMALevel',
 'value_UsHisGMALevel',
 'value_BiologyGMALevel',
 'value_tcapAlgebraILevel',
 'value_tcapAlgebraIILevel',
 'value_tcapBiologyLevel',
 'value_tcapEnglishILevel',
 'value_tcapEnglishIILevel',
 'value_tcapUSHistoryLevel',
 'value_tcapGeographyLevel',
 'value_tcapIntMathILevel',
 'value_tcapIntMathIILevel',
 'value_tcapIntMathIIILevel',
 'value_elsScienceLevel',
 'value_elsScience',
 'value_ELPT',
 'value_ELPTLevel',
 'value_tcapGeometryLevel',
 'value_lexileMilestones',
 'value_lexileRI',
 'value_fsaUsHisLevel',
 'value_fsaScience',
 'value_fsaScienceLevel',
 'value_fsaBioLevel',
 'value_fsaAlgILevel',
 'value_fsaGeometry',
 'value_fsaGeometryLevel',
 'value_fsaCivics',
 'value_fsaCivicsLevel',
 'value_caseEngILevel',
 'value_CBMMathProf',
 'value_lexileStar',
 'value_actWritingScore',
 'value_performanceGeometry',
 'value_performanceEco',
 'value_performanceAlgebraI',
 'value_performanceAlgebraII',
 'value_performancePreCal',
 'value_lexileNWEA',
 'value_MAAPHistoryProf',
 'value_MAAPRLAGr',
 'value_iarELALevel',
 'value_iarMathLevel',
 'value_MAAPMathGr',
 'value_FastELA',
 'value_FastELALevel',
 'value_FastMath',
 'value_FastMathLevel',
 'value_acapLexile',
 'value_StudySyncELA',
 'value_edulasticAlgebra',
 'value_edulasticGeometry',
 'value_edulasticPreCal',
 'value_illuminateSocial',
 'value_illuminateLit',
 'value_illuminatePhysicalScience',
 'value_acapAltMath',
 'value_acapAltELA',
 'value_caseEngLevel',
 'value_edulasticPhySci',
 'value_edulasticBio',
 'value_edulasticChem',
 'value_edulasticEnvironmental',
 'value_edulasticWH',
 'value_edulasticUsHistory',
 'value_edulasticEco',
 'value_edulasticGov',
 'value_edulasticCivics',
 'value_edulasticGeography',
 'value_lexileAchieve',
 'value_MasteryELA',
 'value_MasteryMath',
 'value_CBMVocab',
 'value_CBMWRF',
 'value_caseAlgII',
 'value_caseGeom',
 'value_CMAELA',
 'value_CMAMath',
 'value_CMASci',
 'value_CMASS',
 'value_CMAAlg',
 'value_CMALit',
 'value_CMAPhySci',
 'value_CMABio',
 'value_CMAUsHis',
 'value_ProgressAmLit',
 'value_ProgressUsHis',
 'value_ProgressBio',
 'value_ProgressAlg',
 'value_beableAcademic',
 'value_iReadyReadingPercentile',
 'value_iReadyMathPercentile',
 'value_ESGI',
 'value_EPReading',
 'value_EPMath',
 'value_EPLangArts',
 'value_starReadingUnified',
 'value_ReadyELA',
 'value_ReadyELALevel',
 'value_ReadyRead',
 'value_ReadyReadLevel',
 'value_ReadyMath',
 'value_ReadyMathLevel',
 'value_PassSci',
 'value_PassSciLevel',
 'value_EOCAlgI',
 'value_EOCEngII',
 'value_EOCBioI',
 'value_EOCUsHis',
 'value_WriteScore',
 'value_WINMath',
 'value_WINMathLevel',
 'value_WINData',
 'value_WINDataLevel',
 'value_WINRead',
 'value_WINReadLevel',
 'value_WINSoft',
 'value_starMathUnified',
 'value_starEarlyLitUnified',
 'value_HMHMath',
 'value_edulasticAP',
 'value_exactRead',
 'value_workkeysLevelScore',
 'value_workkeysScaleScore',
 'value_exactMath',
 'value_ProgressLearningScience',
 'value_ProgressLearningSocial',
 'value_ProgressBritLit',
 'value_Progress10thLit',
 'value_ProgressGeo',
 'value_ProgressAMDM',
 'value_ProgressAnatomy',
 'value_ProgressChemistry',
 'value_ProgressEnvironmental',
 'value_ProgressPhysical',
 'value_ProgressEco',
 'value_ProgressAMGov',
 'value_workkeysAMScale',
 'value_workkeysAMLevel',
 'value_workkeysGLScale',
 'value_workkeysGLLevel',
 'value_workkeysWDScale',
 'value_workkeysWDLevel',
 'value_GAAELA',
 'value_GAAELALevel',
 'value_GAAMath',
 'value_GAAMathLevel',
 'value_GAASci',
 'value_GAASciLevel',
 'value_GAASoc',
 'value_GAASocLevel',
 'value_CaseEngIPercentCorrect',
 'value_ProgressELA',
 'value_PassSoc',
 'value_caseMathLevelExt',
 'value_caseReadLevelExt',
 'value_caseEngIILevelExt',
 'value_caseSciLevelExt',
 'value_caseSocLevelExt',
 'value_caseEngILevelExt',
 'value_caseGeoLevelExt',
 'value_caseAlgILevelExt',
 'value_caseAlgIILevelExt',
 'value_caseBioLevelExt',
 'value_EnglishExam',
 'value_PreCalExam',
 'value_AlgIExam',
 'value_AlgIIExam',
 'value_BioExam',
 'value_CalExam',
 'value_PhysicsExam',
 'value_GeomExam',
 'value_AmiraWCPM',
 'value_schoolNetReading',
 'value_schoolNetLanguage',
 'value_starMathPercentile',
 'value_starELPercentile',
 'value_starReadingPercentile',
 'value_TABEMath',
 'value_TABEMathLevel',
 'value_TABEReading',
 'value_TABEMathGE',
 'value_TABEReadingGE',
 'value_TABEReadingLevel',
 'value_GEDMath',
 'value_GEDReasoning',
 'value_GEDScience',
 'value_GEDSS',
 'value_exactLanguage',
 'value_GEDMathLevel',
 'value_GEDReasoningLevel',
 'value_GEDScienceLevel',
 'value_GEDSSLevel',
 'value_BeaconMathLevel',
 'value_BeaconELALevel',
 'value_widaCompLevel',
 'value_GEDReadyMath',
 'value_aimsEarlyLit',
 'value_GEDReadyReasoning',
 'value_GEDReadyReasoningLevel',
 'value_GEDReadySS',
 'value_GEDReadySSLevel',
 'value_IBEnglish',
 'value_IBMath',
 'value_IBScience',
 'value_IBHistory',
 'value_iMSSAReading',
 'value_iMSSALanguage',
 'value_iMSSAMath',
 'value_iMSSAReadingLevel',
 'value_iMSSALanguageLevel',
 'value_iMSSAMathLevel',
 'value_NMMSSALanguage',
 'value_NMMSSAMath',
 'value_NMMSSALanguageLevel',
 'value_NMMSSAMathLevel',
 'value_ProgressPersonalFin',
 'value_ASRLevel',
 'value_ASR',
 'value_AmiraPR',
 'value_AmiraARM',
 'value_PhonicsInventory',
 'value_ProgressMath',
 'value_DibelsCLS',
 'value_NGSS',
 'value_NGSSLevel',
 'value_starLexile',
 'value_Nar360',
 'value_NarLang360',
 'value_ArgOp360',
 'value_ArgLang360',
 'value_gmaElaD1',
 'value_gmaElaD2',
 'value_gmaElaD3',
 'value_gmaElaD4',
 'value_gmaElaD5',
 'value_gmaElaD6',
 'value_gmaElaD7',
 'value_gmaElaD8',
 'value_gmaElaD9',
 'value_gmaMathD1',
 'value_gmaMathD2',
 'value_gmaMathD3',
 'value_gmaMathD4',
 'value_gmaMathD5',
 'value_gmaSciD1',
 'value_gmaSciD2',
 'value_gmaSciD3',
 'value_gmaSciD4',
 'value_gmaSciD5',
 'value_gmaSsD1',
 'value_gmaSsD2',
 'value_gmaSsD3',
 'value_gmaSsD4',
 'value_gmaCalgD1',
 'value_gmaCalgD2',
 'value_gmaCalgD3',
 'value_gmaCalgD4',
 'value_gmaAlg1D1',
 'value_gmaAlg1D2',
 'value_gmaAlg1D3',
 'value_gmaAlg1D4',
 'value_gmaBioD1',
 'value_gmaBioD2',
 'value_gmaBioD3',
 'value_gmaBioD4',
 'value_gmaBioD5',
 'value_gmaUshD1',
 'value_gmaUshD2',
 'value_gmaUshD3',
 'value_gmaUshD4',
 'value_gmaUshD5',
 'value_gmaAmlD1',
 'value_gmaAmlD2',
 'value_gmaAmlD3',
 'value_gmaAmlD4',
 'value_gmaAmlD5',
 'value_gmaAmlD6',
 'value_gmaAmlD7',
 'value_gmaAmlD8',
 'value_gmaAmlD9',
 'value_gmaPhysD1',
 'value_gmaPhysD2',
 'value_gmaPhysD3',
 'value_gmaPhysD4',
 'value_widaComprehension',
 'value_widaComprehensionLevel',
 'value_widaListeningLevel',
 'value_widaLiteracyLevel',
 'value_widaOral',
 'value_widaOralLevel',
 'value_widaCompositeLevel',
 'value_widaReadingLevel',
 'value_widaSpeakingLevel',
 'value_GMAEWI',
 'value_GMAEXGU',
 'value_GMANW',
 'value_WIDAWritingLevel',
 'value_WriteReadNarrER',
 'value_WriteReadNarr',
 'value_WriteID',
 'value_WriteLU',
 'value_GMAWriting',
 'value_AcapElaRc1',
 'value_AcapElaRc2',
 'value_AcapElaRc3',
 'value_AcapElaRc4',
 'value_AcapElaRc5',
 'value_AcapElaRc6',
 'value_AcapElaRc7',
 'value_AcapElaRc8',
 'value_AcapElaRc9',
 'value_AcapElaRc10',
 'value_AcapMathRc1',
 'value_AcapMathRc2',
 'value_AcapMathRc3',
 'value_AcapMathRc4',
 'value_AcapMathRc5',
 'value_maapElaRc1',
 'value_maapElaRc2',
 'value_maapElaRc3',
 'value_maapElaRc4',
 'value_maapElaRc5',
 'value_maapWritingDm1',
 'value_maapWritingDm2',
 'value_maapWritingDm3',
 'value_maapWritingDm4',
 'value_maapMathRc1',
 'value_maapMathRc2',
 'value_maapMathRc3',
 'value_maapMathRc4',
 'value_maapMathRc5',
 'value_maapScienceRc1',
 'value_maapScienceRc2',
 'value_maapScienceRc3',
 'value_maapBioRc1',
 'value_maapBioRc2',
 'value_maapBioRc3',
 'value_maapUshRc1',
 'value_maapUshRc2',
 'value_maapUshRc3',
 'value_maapUshRc4',
 'value_maapUshRc5',
 'value_ESGIMath',
 'value_RGRPAvg',
 'value_RGRPhoAwaAvg',
 'value_acapAltMathLevel',
 'value_acapAltELALevel',
 'value_acapAltSci',
 'value_acapAltSciLevel',
 'value_ESGIsightwords',
 'value_MaapAlgIGrowth',
 'value_MaapEngIIGrowth',
 'value_cltVerbalReasoning',
 'value_cltQuantitativeReasoning',
 'value_cltGRWR',
 'value_cltComposite',
 'value_NMMSSAReading',
 'value_NMMSSAReadingLevel',
 'value_NMMSSAWriting',
 'value_NMMSSAWritingLevel',
 'value_NMMSSAReadingGrowth',
 'value_NMMSSAWritingGrowth',
 'value_NMMSSALanguageGrowth',
 'value_NMMSSAMathGrowth',
 'value_iMSSAReadingGrowth',
 'value_iMSSALanguageGrowth',
 'value_iMSSAMathGrowth',
 'value_CaasppMath',
 'value_CaasppMathLevel',
 'value_CaasppELA',
 'value_CaaspELALevel',
 'value_Cast',
 'value_CastLevel',
 'value_CaasppLexile',
 'value_CaasppQuantile',
 'value_Elpac',
 'value_ElpacLevel',
 'value_ElpacOral',
 'value_ElpacOralLevel',
 'value_ElpacWritten',
 'value_ElpacWrittenLevel',
 'value_AcapSciRc1',
 'value_AcapSciRc2',
 'value_AcapSciRc3',
 'value_AcapSciRc4',
 'value_fsaWriting',
 'value_fsaWritingLevel',
 'value_acadienceReadingCompositeLevel']

In [72]:
df_scores.isnull().sum()

id                                      0
districtId                              0
subgroup_TCAPELALevel                   0
ticket                                  0
studentId                               0
                                       ..
value_AcapSciRc3                        0
value_AcapSciRc4                        0
value_fsaWriting                        0
value_fsaWritingLevel                   0
value_acadienceReadingCompositeLevel    0
Length: 715, dtype: int64

In [73]:
df_scores.dtypes

id                                       int64
districtId                               int64
subgroup_TCAPELALevel                    int64
ticket                                  object
studentId                                int64
                                         ...
value_AcapSciRc3                         int64
value_AcapSciRc4                         int64
value_fsaWriting                         int64
value_fsaWritingLevel                    int64
value_acadienceReadingCompositeLevel     int64
Length: 715, dtype: object

In [74]:
df_scores.describe()

,id,districtId,subgroup_TCAPELALevel,studentId,studentLevel,year,measurementTypeId,subgroup_specialEd,subgroup_lunchStatus,subgroup_gender,...,value_ElpacOralLevel,value_ElpacWritten,value_ElpacWrittenLevel,value_AcapSciRc1,value_AcapSciRc2,value_AcapSciRc3,value_AcapSciRc4,value_fsaWriting,value_fsaWritingLevel,value_acadienceReadingCompositeLevel
count,1.322580e+05,132258.0,132258.0,1.322580e+05,132258.000000,132258.0,132258.000000,132258.000000,132258.0,132258.000000,...,132258.0,132258.0,132258.0,132258.000000,132258.000000,132258.000000,132258.000000,132258.0,132258.0,132258.0
mean,6.834470e+06,18.0,0.0,1.541963e+06,5.461598,2023.0,8.945236,2.163234,0.0,1.198755,...,0.0,0.0,0.0,0.036860,0.035831,0.036852,0.025034,0.0,0.0,0.0
std,1.183278e+06,0.0,0.0,1.858547e+05,2.903078,0.0,6.197672,1.240002,0.0,0.731720,...,0.0,0.0,0.0,0.283307,0.277290,0.283694,0.234198,0.0,0.0,0.0
min,3.267831e+06,18.0,0.0,1.480117e+06,-1.000000,2023.0,1.000000,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
25%,5.445422e+06,18.0,0.0,1.484688e+06,3.000000,2023.0,4.000000,1.000000,0.0,1.000000,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
50%,7.626116e+06,18.0,0.0,1.487101e+06,5.000000,2023.0,8.000000,3.000000,0.0,1.000000,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
75%,7.678102e+06,18.0,0.0,1.489734e+06,8.000000,2023.0,13.000000,3.000000,0.0,2.000000,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
max,8.827091e+06,18.0,0.0,2.513590e+06,62.000000,2023.0,40.000000,3.000000,0.0,2.000000,...,0.0,0.0,0.0,3.000000,3.000000,3.000000,3.000000,0.0,0.0,0.0

In [75]:
# Created a new DataFrame with subgroup columns
subgroup_df = df_scores[['subgroup_specialEd', 'subgroup_lunchStatus', 'subgroup_gender', 'subgroup_ethnicity', 'subgroup_ell', 'subGroup_bottom25']]

subgroup_df.head()

,subgroup_specialEd,subgroup_lunchStatus,subgroup_gender,subgroup_ethnicity,subgroup_ell,subGroup_bottom25
0,0,0,0,0,0,0
1,0,0,0,0,0,0
2,0,0,0,0,0,0
3,0,0,0,0,0,0
4,0,0,0,0,0,0

In [76]:
subgroup_df.shape

(132258, 6)

In [77]:
subgroup_df.describe()

,subgroup_specialEd,subgroup_lunchStatus,subgroup_gender,subgroup_ethnicity,subgroup_ell,subGroup_bottom25
count,132258.000000,132258.0,132258.000000,132258.0,132258.000000,132258.0
mean,2.163234,0.0,1.198755,0.0,1.590308,0.0
std,1.240002,0.0,0.731720,0.0,0.786135,0.0
min,0.000000,0.0,0.000000,0.0,0.000000,0.0
25%,1.000000,0.0,1.000000,0.0,2.000000,0.0
50%,3.000000,0.0,1.000000,0.0,2.000000,0.0
75%,3.000000,0.0,2.000000,0.0,2.000000,0.0
max,3.000000,0.0,2.000000,0.0,2.000000,0.0

In [78]:
df_scores['studentLevel'].describe()

count    132258.000000
mean          5.461598
std           2.903078
min          -1.000000
25%           3.000000
50%           5.000000
75%           8.000000
max          62.000000
Name: studentLevel, dtype: float64

In [9]:
# prompt: correlate df_vut[‘name’] with df_scores[‘studentLevel’]

# Merge the two DataFrames based on a common column (if one exists).
# If there is no common column, you can create one or explore other methods to correlate them.
# For example, you could try to create a new column in both DataFrames to represent the
# same thing, and then merge them on this new column.

# Assuming there is a common column named 'common_column' in both DataFrames
# merged_df = pd.merge(df_vut, df_scores, on='common_column', how='inner')

# If there is no common column, we can create a dummy column to merge on.
df_vut['dummy_column'] = 1
df_scores['dummy_column'] = 1
merged_df = pd.merge(df_vut, df_scores, on='dummy_column', how='inner')


# Now you can calculate the correlation between the two columns
correlation = merged_df['name'].corr(merged_df['studentLevel'])

print(f"Correlation between df_vut['name'] and df_scores['studentLevel'] : {correlation}")

NameError: name 'df_vut' is not defined